parallel processing

diff --git a/Advanced_shell/batchProcessing-0x04 b/Advanced_shell/batchProcessing-0x04
--- a/Advanced_shell/batchProcessing-0x04
+++ b/Advanced_shell/batchProcessing-0x04
@@ -20,12 +20,21 @@ fetch_pokemon()  {
 	fi
 }
 
+pids=()
+
 for pokemon in "${pokemon_list[@]}"; do
 	fetch_pokemon "$pokemon" &
+	pids+=($!)
+done
+
+for pid in "${pids[@]}"; do
+	if ! kill -0 "$pid" 2>/dev/null; then
+		echo "Process $pid is not running"
+	fi
 done
 
 #---------wait for all parrallel jobs to finish____#
 wait
 
 echo "Complete"
-echo "check the pokemon name with extension .json and errors.txt for errors"
+echo "check *.json files and errors.txt for errors"
